### ISSUE TITLE
Possible Name change to avoid confusion with OpenMalariaTools ?

### ISSUE THREAD

**Issue by tph-thuering** [vecnet/openmalaria.tools#3]
see: https://github.com/SwissTPH/openmalaria/wiki/openmalariaTools

**Comment by Baguage** [comment]
Good point. Any suggestions for a new name? I will think about it too.

**Comment by tph-thuering** [comment]
**utility belt**
openmalaria.utility-belt

**tool bag**
openmalaria.tool-bag

**wrench**
openmalaria.wrench

**magic**
openmalaria.magic

**foo**
openmalaria.foo

**Comment by dhardy** [comment]
Apparently I'm still watching this ;!

Guillaume's openmalariaTools (that @tph-thuering mentioned) hasn't been used much in a while AFAIK, so I wouldn't worry much.
